# ClusterIssuer for step-ca
# This connects cert-manager to step-ca for automatic certificate issuance
# Deployed automatically by k3s

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca
spec:
  acme:
    # Use step-ca's ACME server
    server: https://step-certificates.step-ca.svc.cluster.local/acme/acme/directory
    # Email for ACME registration (change as needed)
    email: admin@nubita.local
    privateKeySecretRef:
      name: step-ca-acme-account
    # Skip TLS verification for internal CA
    skipTLSVerify: true
    # Disable self-check for .local domains that may not resolve in-cluster
    disableAccountKeyGeneration: false
    solvers:
    - http01:
        ingress:
          class: traefik
          podTemplate:
            metadata:
              annotations:
                # Disable ingress self-check
                "acme.cert-manager.io/http01-override-ingress-name": "true"
