# ClusterIssuer for step-ca
# This connects cert-manager to step-ca for automatic certificate issuance
# Deployed automatically by k3s

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca
spec:
  ca:
    secretName: step-certificates-ca-password
